// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPK-xuX3e7BfaSi4nnxBf8DLaC_1kJA8',
    appId: '1:782054312745:web:cc51aa2fcc947556c78538',
    messagingSenderId: '782054312745',
    projectId: 'jeeguide-47765',
    authDomain: 'jeeguide-47765.firebaseapp.com',
    storageBucket: 'jeeguide-47765.firebasestorage.app',
    measurementId: 'G-F6FF11YPXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgjBjQ6YUmnAmtbgAeYKSe-XhFzEIcaE',
    appId: '1:782054312745:android:1ae55b0daa5cefa3c78538',
    messagingSenderId: '782054312745',
    projectId: 'jeeguide-47765',
    storageBucket: 'jeeguide-47765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bi4wNuSF6-ntEMdoLpE3MSgH2j8UTA8',
    appId: '1:782054312745:ios:2742cc3b967c4925c78538',
    messagingSenderId: '782054312745',
    projectId: 'jeeguide-47765',
    storageBucket: 'jeeguide-47765.firebasestorage.app',
    iosClientId: '782054312745-v4stl8aj7h3d07d2uf8q7gh0qtu7l6jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeeCounsellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bi4wNuSF6-ntEMdoLpE3MSgH2j8UTA8',
    appId: '1:782054312745:ios:2742cc3b967c4925c78538',
    messagingSenderId: '782054312745',
    projectId: 'jeeguide-47765',
    storageBucket: 'jeeguide-47765.firebasestorage.app',
    iosClientId: '782054312745-v4stl8aj7h3d07d2uf8q7gh0qtu7l6jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeeCounsellingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPK-xuX3e7BfaSi4nnxBf8DLaC_1kJA8',
    appId: '1:782054312745:web:22388e235449839fc78538',
    messagingSenderId: '782054312745',
    projectId: 'jeeguide-47765',
    authDomain: 'jeeguide-47765.firebaseapp.com',
    storageBucket: 'jeeguide-47765.firebasestorage.app',
    measurementId: 'G-RJPGEKXTT1',
  );
}
